### ISSUE TITLE
Issue 19: Get rid of html/template because it's unsafe and hard to check

### ISSUE THREAD

**Issue by ghost** [1f604/supersimplewiki#34]
html/template is unsafe in that it allows you to pass incorrect structs to parsed templates and apparently there is no way to validate this at compile time. This is more flexibility than we need and it's unsafe.

Nesting templates also seems more complicated than it needs to be and somewhat confusing too.

Given these considerations I think the code would be easier to understand and more straightforward if we get rid of html/template and just concatenate variables directly into HTML string.

This would have the advantage that nesting templates e.g. having a "header" that we put on many pages would be straightforward to implement in a natural way using easy-to-understand Go instead of some template magic.

**Comment by 1f604** [comment]
So we are going to use string concatenation which is easier to understand but is vulnerable to injection attacks?

**Comment by 1f604-dev** [comment]
Users are already exposed to XSS and CSRF attacks so this won't make things worse.

Serverside injection attacks should be impossible by design. We are only concatenating strings to send to the user, we're not executing the strings.

**Comment by 1f604** [comment]
We are no longer using html/template.
